DB_NAME = "research-base"
MYSQL_DB_NAME = "research-base"
DB_IP = "172.208.27.84"
DB_PORT = 8000
CHUNK_SIZE = 1500
UPLOADS_FOLDER="../server/uploads"
BASE_PATH="../server"
SERVER_URL="http://localhost:5000"
PDF_FILES_FOLDER="~/files/"